DATA_ABILITY = {
    'strength': {
        1:  {'hit_probability': -5, 'damage_adjust': -4, 'weight_allowance':    1, 'max_press':    3, 'open_doors':  1, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        2:  {'hit_probability': -3, 'damage_adjust': -2, 'weight_allowance':    1, 'max_press':    5, 'open_doors':  1, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        3:  {'hit_probability': -3, 'damage_adjust': -1, 'weight_allowance':    5, 'max_press':   10, 'open_doors':  2, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        4:  {'hit_probability': -2, 'damage_adjust': -1, 'weight_allowance':   10, 'max_press':   25, 'open_doors':  3, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        5:  {'hit_probability': -2, 'damage_adjust': -1, 'weight_allowance':   10, 'max_press':   25, 'open_doors':  3, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        6:  {'hit_probability': -1, 'damage_adjust':  0, 'weight_allowance':   20, 'max_press':   55, 'open_doors':  4, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        7:  {'hit_probability': -1, 'damage_adjust':  0, 'weight_allowance':   20, 'max_press':   55, 'open_doors':  4, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        8:  {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   35, 'max_press':   90, 'open_doors':  5, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 1},
        9:  {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   35, 'max_press':   90, 'open_doors':  5, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 1},
        10: {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   40, 'max_press':  115, 'open_doors':  6, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 2},
        11: {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   40, 'max_press':  115, 'open_doors':  6, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 2},
        12: {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   45, 'max_press':  140, 'open_doors':  7, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 4},
        13: {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   45, 'max_press':  140, 'open_doors':  7, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 4},
        14: {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   55, 'max_press':  170, 'open_doors':  8, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 7},
        15: {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   55, 'max_press':  170, 'open_doors':  8, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 7},
        16: {'hit_probability':  0, 'damage_adjust':  1, 'weight_allowance':   70, 'max_press':  195, 'open_doors':  9, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 10},
        17: {'hit_probability':  1, 'damage_adjust':  1, 'weight_allowance':   85, 'max_press':  220, 'open_doors': 10, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 13},
        18: {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        19: {'hit_probability':  3, 'damage_adjust':  7, 'weight_allowance':  485, 'max_press':  640, 'open_doors': 16, 'open_doors_locked_magic':  8, 'bend_bars_lift_gates': 50},
        20: {'hit_probability':  3, 'damage_adjust':  8, 'weight_allowance':  535, 'max_press':  700, 'open_doors': 17, 'open_doors_locked_magic': 10, 'bend_bars_lift_gates': 60},
        21: {'hit_probability':  4, 'damage_adjust':  9, 'weight_allowance':  635, 'max_press':  810, 'open_doors': 17, 'open_doors_locked_magic': 12, 'bend_bars_lift_gates': 70},
        22: {'hit_probability':  4, 'damage_adjust': 10, 'weight_allowance':  785, 'max_press':  970, 'open_doors': 18, 'open_doors_locked_magic': 14, 'bend_bars_lift_gates': 80},
        23: {'hit_probability':  5, 'damage_adjust': 11, 'weight_allowance':  935, 'max_press': 1130, 'open_doors': 18, 'open_doors_locked_magic': 16, 'bend_bars_lift_gates': 90},
        24: {'hit_probability':  6, 'damage_adjust': 12, 'weight_allowance': 1235, 'max_press': 1440, 'open_doors': 19, 'open_doors_locked_magic': 17, 'bend_bars_lift_gates': 95},
        25: {'hit_probability':  7, 'damage_adjust': 14, 'weight_allowance': 1535, 'max_press': 1750, 'open_doors': 19, 'open_doors_locked_magic': 18, 'bend_bars_lift_gates': 99}
    },
    'dexterity': {
        1:  {'reaction_adjust': -6, 'missile_attack_adjust': -6, 'defensive_adjust':  5},
        2:  {'reaction_adjust': -4, 'missile_attack_adjust': -4, 'defensive_adjust':  5},
        3:  {'reaction_adjust': -3, 'missile_attack_adjust': -3, 'defensive_adjust':  4},
        4:  {'reaction_adjust': -2, 'missile_attack_adjust': -2, 'defensive_adjust':  3},
        5:  {'reaction_adjust': -1, 'missile_attack_adjust': -1, 'defensive_adjust':  2},
        6:  {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  1},
        7:  {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0},
        8:  {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0},
        9:  {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0},
        10: {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0},
        11: {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0},
        12: {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0},
        13: {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0},
        14: {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0},
        15: {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust': -1},
        16: {'reaction_adjust':  1, 'missile_attack_adjust':  1, 'defensive_adjust': -2},
        17: {'reaction_adjust':  2, 'missile_attack_adjust':  2, 'defensive_adjust': -3},
        18: {'reaction_adjust':  2, 'missile_attack_adjust':  2, 'defensive_adjust': -4},
        19: {'reaction_adjust':  3, 'missile_attack_adjust':  3, 'defensive_adjust': -4},
        20: {'reaction_adjust':  3, 'missile_attack_adjust':  3, 'defensive_adjust': -4},
        21: {'reaction_adjust':  4, 'missile_attack_adjust':  4, 'defensive_adjust': -5},
        22: {'reaction_adjust':  4, 'missile_attack_adjust':  4, 'defensive_adjust': -5},
        23: {'reaction_adjust':  4, 'missile_attack_adjust':  4, 'defensive_adjust': -5},
        24: {'reaction_adjust':  5, 'missile_attack_adjust':  5, 'defensive_adjust': -6},
        25: {'reaction_adjust':  5, 'missile_attack_adjust':  5, 'defensive_adjust': -6}
    },
    'constitution': {
    },
    'intelligence': {
    },
    'wisdom': {
    },
    'charisma': {
    }
}