DATA_ABILITY = {
    'strength': {
        '1':  {'hit_probability': -5, 'damage_adjust': -4, 'weight_allowance':    1, 'max_press':    3, 'open_doors':  1, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        '2':  {'hit_probability': -3, 'damage_adjust': -2, 'weight_allowance':    1, 'max_press':    5, 'open_doors':  1, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        '3':  {'hit_probability': -3, 'damage_adjust': -1, 'weight_allowance':    5, 'max_press':   10, 'open_doors':  2, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        '4':  {'hit_probability': -2, 'damage_adjust': -1, 'weight_allowance':   10, 'max_press':   25, 'open_doors':  3, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        '5':  {'hit_probability': -2, 'damage_adjust': -1, 'weight_allowance':   10, 'max_press':   25, 'open_doors':  3, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        '6':  {'hit_probability': -1, 'damage_adjust':  0, 'weight_allowance':   20, 'max_press':   55, 'open_doors':  4, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        '7':  {'hit_probability': -1, 'damage_adjust':  0, 'weight_allowance':   20, 'max_press':   55, 'open_doors':  4, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 0},
        '8':  {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   35, 'max_press':   90, 'open_doors':  5, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 1},
        '9':  {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   35, 'max_press':   90, 'open_doors':  5, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 1},
        '10': {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   40, 'max_press':  115, 'open_doors':  6, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 2},
        '11': {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   40, 'max_press':  115, 'open_doors':  6, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 2},
        '12': {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   45, 'max_press':  140, 'open_doors':  7, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 4},
        '13': {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   45, 'max_press':  140, 'open_doors':  7, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 4},
        '14': {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   55, 'max_press':  170, 'open_doors':  8, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 7},
        '15': {'hit_probability':  0, 'damage_adjust':  0, 'weight_allowance':   55, 'max_press':  170, 'open_doors':  8, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 7},
        '16': {'hit_probability':  0, 'damage_adjust':  1, 'weight_allowance':   70, 'max_press':  195, 'open_doors':  9, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 10},
        '17': {'hit_probability':  1, 'damage_adjust':  1, 'weight_allowance':   85, 'max_press':  220, 'open_doors': 10, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 13},
        '18': {'hit_probability':  1, 'damage_adjust':  2, 'weight_allowance':  110, 'max_press':  255, 'open_doors': 11, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 16},
        '18/01': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/02': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/03': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/04': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/05': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/06': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/07': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/08': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/09': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/10': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/11': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/12': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/13': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/14': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/15': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/16': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/17': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/18': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/19': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/20': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/21': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/22': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/23': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/24': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/25': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/26': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/27': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/28': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/29': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/30': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/31': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/32': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/33': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/34': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/35': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/36': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/37': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/38': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/39': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/40': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/41': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/42': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/43': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/44': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/45': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/46': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/47': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/48': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/49': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/50': {'hit_probability':  1, 'damage_adjust':  3, 'weight_allowance':  135, 'max_press':  280, 'open_doors': 12, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 20},
        '18/51': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/52': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/53': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/54': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/55': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/56': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/57': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/58': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/59': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/60': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/61': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/62': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/63': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/64': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/65': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/66': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/67': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/68': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/69': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/70': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/71': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/72': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/73': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/74': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/75': {'hit_probability':  2, 'damage_adjust':  3, 'weight_allowance':  160, 'max_press':  305, 'open_doors': 13, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 25},
        '18/76': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/77': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/78': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/79': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/80': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/81': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/82': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/83': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/84': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/85': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/86': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/87': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/88': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/89': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/90': {'hit_probability':  2, 'damage_adjust':  4, 'weight_allowance':  185, 'max_press':  330, 'open_doors': 14, 'open_doors_locked_magic':  0, 'bend_bars_lift_gates': 30},
        '18/91': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/92': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/93': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/94': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/95': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/96': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/97': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/98': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/99': {'hit_probability':  2, 'damage_adjust':  5, 'weight_allowance':  235, 'max_press':  380, 'open_doors': 15, 'open_doors_locked_magic':  3, 'bend_bars_lift_gates': 35},
        '18/00': {'hit_probability':  3, 'damage_adjust':  6, 'weight_allowance':  335, 'max_press':  480, 'open_doors': 16, 'open_doors_locked_magic':  6, 'bend_bars_lift_gates': 40},
        '19': {'hit_probability':  3, 'damage_adjust':  7, 'weight_allowance':  485, 'max_press':  640, 'open_doors': 16, 'open_doors_locked_magic':  8, 'bend_bars_lift_gates': 50},
        '20': {'hit_probability':  3, 'damage_adjust':  8, 'weight_allowance':  535, 'max_press':  700, 'open_doors': 17, 'open_doors_locked_magic': 10, 'bend_bars_lift_gates': 60},
        '21': {'hit_probability':  4, 'damage_adjust':  9, 'weight_allowance':  635, 'max_press':  810, 'open_doors': 17, 'open_doors_locked_magic': 12, 'bend_bars_lift_gates': 70},
        '22': {'hit_probability':  4, 'damage_adjust': 10, 'weight_allowance':  785, 'max_press':  970, 'open_doors': 18, 'open_doors_locked_magic': 14, 'bend_bars_lift_gates': 80},
        '23': {'hit_probability':  5, 'damage_adjust': 11, 'weight_allowance':  935, 'max_press': 1130, 'open_doors': 18, 'open_doors_locked_magic': 16, 'bend_bars_lift_gates': 90},
        '24': {'hit_probability':  6, 'damage_adjust': 12, 'weight_allowance': 1235, 'max_press': 1440, 'open_doors': 19, 'open_doors_locked_magic': 17, 'bend_bars_lift_gates': 95},
        '25': {'hit_probability':  7, 'damage_adjust': 14, 'weight_allowance': 1535, 'max_press': 1750, 'open_doors': 19, 'open_doors_locked_magic': 18, 'bend_bars_lift_gates': 99}
    },
    'dexterity': {
        '1':  {'reaction_adjust': -6, 'missile_attack_adjust': -6, 'defensive_adjust':  5, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '2':  {'reaction_adjust': -4, 'missile_attack_adjust': -4, 'defensive_adjust':  5, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '3':  {'reaction_adjust': -3, 'missile_attack_adjust': -3, 'defensive_adjust':  4, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '4':  {'reaction_adjust': -2, 'missile_attack_adjust': -2, 'defensive_adjust':  3, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '5':  {'reaction_adjust': -1, 'missile_attack_adjust': -1, 'defensive_adjust':  2, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '6':  {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  1, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '7':  {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '8':  {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '9':  {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0, 'thief_pick_pockets': -15, 'thief_open_locks': -10, 'thief_find_remove_traps': -10, 'thief_move_silently': -20, 'thief_hide_shadows': -10},
        '10': {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0, 'thief_pick_pockets': -10, 'thief_open_locks':  -5, 'thief_find_remove_traps': -10, 'thief_move_silently': -15, 'thief_hide_shadows':  -5},
        '11': {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0, 'thief_pick_pockets':  -5, 'thief_open_locks':   0, 'thief_find_remove_traps':  -5, 'thief_move_silently': -10, 'thief_hide_shadows':   0},
        '12': {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0, 'thief_pick_pockets':   0, 'thief_open_locks':   0, 'thief_find_remove_traps':   0, 'thief_move_silently':  -5, 'thief_hide_shadows':   0},
        '13': {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0, 'thief_pick_pockets':   0, 'thief_open_locks':   0, 'thief_find_remove_traps':   0, 'thief_move_silently':   0, 'thief_hide_shadows':   0},
        '14': {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust':  0, 'thief_pick_pockets':   0, 'thief_open_locks':   0, 'thief_find_remove_traps':   0, 'thief_move_silently':   0, 'thief_hide_shadows':   0},
        '15': {'reaction_adjust':  0, 'missile_attack_adjust':  0, 'defensive_adjust': -1, 'thief_pick_pockets':   0, 'thief_open_locks':   0, 'thief_find_remove_traps':   0, 'thief_move_silently':   0, 'thief_hide_shadows':   0},
        '16': {'reaction_adjust':  1, 'missile_attack_adjust':  1, 'defensive_adjust': -2, 'thief_pick_pockets':   0, 'thief_open_locks':   5, 'thief_find_remove_traps':   0, 'thief_move_silently':   0, 'thief_hide_shadows':   0},
        '17': {'reaction_adjust':  2, 'missile_attack_adjust':  2, 'defensive_adjust': -3, 'thief_pick_pockets':   5, 'thief_open_locks':  10, 'thief_find_remove_traps':   0, 'thief_move_silently':   5, 'thief_hide_shadows':   5},
        '18': {'reaction_adjust':  2, 'missile_attack_adjust':  2, 'defensive_adjust': -4, 'thief_pick_pockets':  10, 'thief_open_locks':  15, 'thief_find_remove_traps':   5, 'thief_move_silently':  10, 'thief_hide_shadows':  10},
        '19': {'reaction_adjust':  3, 'missile_attack_adjust':  3, 'defensive_adjust': -4, 'thief_pick_pockets':  15, 'thief_open_locks':  20, 'thief_find_remove_traps':  10, 'thief_move_silently':  15, 'thief_hide_shadows':  15},
        '20': {'reaction_adjust':  3, 'missile_attack_adjust':  3, 'defensive_adjust': -4, 'thief_pick_pockets':  15, 'thief_open_locks':  20, 'thief_find_remove_traps':  10, 'thief_move_silently':  15, 'thief_hide_shadows':  15},
        '21': {'reaction_adjust':  4, 'missile_attack_adjust':  4, 'defensive_adjust': -5, 'thief_pick_pockets':  15, 'thief_open_locks':  20, 'thief_find_remove_traps':  10, 'thief_move_silently':  15, 'thief_hide_shadows':  15},
        '22': {'reaction_adjust':  4, 'missile_attack_adjust':  4, 'defensive_adjust': -5, 'thief_pick_pockets':  15, 'thief_open_locks':  20, 'thief_find_remove_traps':  10, 'thief_move_silently':  15, 'thief_hide_shadows':  15},
        '23': {'reaction_adjust':  4, 'missile_attack_adjust':  4, 'defensive_adjust': -5, 'thief_pick_pockets':  15, 'thief_open_locks':  20, 'thief_find_remove_traps':  10, 'thief_move_silently':  15, 'thief_hide_shadows':  15},
        '24': {'reaction_adjust':  5, 'missile_attack_adjust':  5, 'defensive_adjust': -6, 'thief_pick_pockets':  15, 'thief_open_locks':  20, 'thief_find_remove_traps':  10, 'thief_move_silently':  15, 'thief_hide_shadows':  15},
        '25': {'reaction_adjust':  5, 'missile_attack_adjust':  5, 'defensive_adjust': -6, 'thief_pick_pockets':  15, 'thief_open_locks':  20, 'thief_find_remove_traps':  10, 'thief_move_silently':  15, 'thief_hide_shadows':  15}
    },
    'constitution': {
        '1':  {'hit_point_adjust': -3, 'hit_point_adjust_warrior': -3, 'system_shock':  25, 'resurrection_survival':  30, 'poison_save': -2, 'regeneration': '-'},
        '2':  {'hit_point_adjust': -2, 'hit_point_adjust_warrior': -2, 'system_shock':  30, 'resurrection_survival':  35, 'poison_save': -1, 'regeneration': '-'},
        '3':  {'hit_point_adjust': -2, 'hit_point_adjust_warrior': -2, 'system_shock':  35, 'resurrection_survival':  40, 'poison_save':  0, 'regeneration': '-'},
        '4':  {'hit_point_adjust': -1, 'hit_point_adjust_warrior': -1, 'system_shock':  40, 'resurrection_survival':  45, 'poison_save':  0, 'regeneration': '-'},
        '5':  {'hit_point_adjust': -1, 'hit_point_adjust_warrior': -1, 'system_shock':  45, 'resurrection_survival':  50, 'poison_save':  0, 'regeneration': '-'},
        '6':  {'hit_point_adjust': -1, 'hit_point_adjust_warrior': -1, 'system_shock':  50, 'resurrection_survival':  55, 'poison_save':  0, 'regeneration': '-'},
        '7':  {'hit_point_adjust':  0, 'hit_point_adjust_warrior':  0, 'system_shock':  55, 'resurrection_survival':  60, 'poison_save':  0, 'regeneration': '-'},
        '8':  {'hit_point_adjust':  0, 'hit_point_adjust_warrior':  0, 'system_shock':  60, 'resurrection_survival':  65, 'poison_save':  0, 'regeneration': '-'},
        '9':  {'hit_point_adjust':  0, 'hit_point_adjust_warrior':  0, 'system_shock':  65, 'resurrection_survival':  70, 'poison_save':  0, 'regeneration': '-'},
        '10': {'hit_point_adjust':  0, 'hit_point_adjust_warrior':  0, 'system_shock':  70, 'resurrection_survival':  75, 'poison_save':  0, 'regeneration': '-'},
        '11': {'hit_point_adjust':  0, 'hit_point_adjust_warrior':  0, 'system_shock':  75, 'resurrection_survival':  80, 'poison_save':  0, 'regeneration': '-'},
        '12': {'hit_point_adjust':  0, 'hit_point_adjust_warrior':  0, 'system_shock':  80, 'resurrection_survival':  85, 'poison_save':  0, 'regeneration': '-'},
        '13': {'hit_point_adjust':  0, 'hit_point_adjust_warrior':  0, 'system_shock':  85, 'resurrection_survival':  90, 'poison_save':  0, 'regeneration': '-'},
        '14': {'hit_point_adjust':  0, 'hit_point_adjust_warrior':  0, 'system_shock':  88, 'resurrection_survival':  92, 'poison_save':  0, 'regeneration': '-'},
        '15': {'hit_point_adjust':  1, 'hit_point_adjust_warrior':  1, 'system_shock':  90, 'resurrection_survival':  94, 'poison_save':  0, 'regeneration': '-'},
        '16': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  2, 'system_shock':  95, 'resurrection_survival':  96, 'poison_save':  0, 'regeneration': '-'},
        '17': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  3, 'system_shock':  97, 'resurrection_survival':  98, 'poison_save':  0, 'regeneration': '-'},
        '18': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  4, 'system_shock':  99, 'resurrection_survival': 100, 'poison_save':  0, 'regeneration': '-'},
        '19': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  5, 'system_shock':  99, 'resurrection_survival': 100, 'poison_save':  1, 'regeneration': '-'},
        '20': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  5, 'system_shock':  99, 'resurrection_survival': 100, 'poison_save':  1, 'regeneration': '1/6'},
        '21': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  6, 'system_shock':  99, 'resurrection_survival': 100, 'poison_save':  2, 'regeneration': '1/5'},
        '22': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  6, 'system_shock':  99, 'resurrection_survival': 100, 'poison_save':  2, 'regeneration': '1/4'},
        '23': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  6, 'system_shock':  99, 'resurrection_survival': 100, 'poison_save':  3, 'regeneration': '1/3'},
        '24': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  7, 'system_shock':  99, 'resurrection_survival': 100, 'poison_save':  3, 'regeneration': '1/2'},
        '25': {'hit_point_adjust':  2, 'hit_point_adjust_warrior':  7, 'system_shock': 100, 'resurrection_survival': 100, 'poison_save':  4, 'regeneration': '1/1'}
    },
    'intelligence': {
        '1':  {'num_languages':  0, 'spell_level': 0, 'learn_spell_chance':   0, 'max_spells_per_level':   0, 'spell_immunity': ''},
        '2':  {'num_languages':  1, 'spell_level': 0, 'learn_spell_chance':   0, 'max_spells_per_level':   0, 'spell_immunity': ''},
        '3':  {'num_languages':  1, 'spell_level': 0, 'learn_spell_chance':   0, 'max_spells_per_level':   0, 'spell_immunity': ''},
        '4':  {'num_languages':  1, 'spell_level': 0, 'learn_spell_chance':   0, 'max_spells_per_level':   0, 'spell_immunity': ''},
        '5':  {'num_languages':  1, 'spell_level': 0, 'learn_spell_chance':   0, 'max_spells_per_level':   0, 'spell_immunity': ''},
        '6':  {'num_languages':  1, 'spell_level': 0, 'learn_spell_chance':   0, 'max_spells_per_level':   0, 'spell_immunity': ''},
        '7':  {'num_languages':  1, 'spell_level': 0, 'learn_spell_chance':   0, 'max_spells_per_level':   0, 'spell_immunity': ''},
        '8':  {'num_languages':  1, 'spell_level': 0, 'learn_spell_chance':   0, 'max_spells_per_level':   0, 'spell_immunity': ''},
        '9':  {'num_languages':  2, 'spell_level': 4, 'learn_spell_chance':  35, 'max_spells_per_level':   6, 'spell_immunity': ''},
        '10': {'num_languages':  2, 'spell_level': 5, 'learn_spell_chance':  40, 'max_spells_per_level':   7, 'spell_immunity': ''},
        '11': {'num_languages':  2, 'spell_level': 5, 'learn_spell_chance':  45, 'max_spells_per_level':   7, 'spell_immunity': ''},
        '12': {'num_languages':  3, 'spell_level': 6, 'learn_spell_chance':  50, 'max_spells_per_level':   7, 'spell_immunity': ''},
        '13': {'num_languages':  3, 'spell_level': 6, 'learn_spell_chance':  55, 'max_spells_per_level':   9, 'spell_immunity': ''},
        '14': {'num_languages':  4, 'spell_level': 7, 'learn_spell_chance':  60, 'max_spells_per_level':   9, 'spell_immunity': ''},
        '15': {'num_languages':  4, 'spell_level': 7, 'learn_spell_chance':  65, 'max_spells_per_level':  11, 'spell_immunity': ''},
        '16': {'num_languages':  5, 'spell_level': 8, 'learn_spell_chance':  70, 'max_spells_per_level':  11, 'spell_immunity': ''},
        '17': {'num_languages':  6, 'spell_level': 8, 'learn_spell_chance':  75, 'max_spells_per_level':  14, 'spell_immunity': ''},
        '18': {'num_languages':  7, 'spell_level': 9, 'learn_spell_chance':  85, 'max_spells_per_level':  18, 'spell_immunity': ''},
        '19': {'num_languages':  8, 'spell_level': 9, 'learn_spell_chance':  95, 'max_spells_per_level': 100, 'spell_immunity': '1st LvL Illusions'},
        '20': {'num_languages':  9, 'spell_level': 9, 'learn_spell_chance':  96, 'max_spells_per_level': 100, 'spell_immunity': '2nd LvL Illusions'},
        '21': {'num_languages': 10, 'spell_level': 9, 'learn_spell_chance':  97, 'max_spells_per_level': 100, 'spell_immunity': '3rd LvL Illusions'},
        '22': {'num_languages': 11, 'spell_level': 9, 'learn_spell_chance':  98, 'max_spells_per_level': 100, 'spell_immunity': '4th LvL Illusions'},
        '23': {'num_languages': 12, 'spell_level': 9, 'learn_spell_chance':  99, 'max_spells_per_level': 100, 'spell_immunity': '5th LvL Illusions'},
        '24': {'num_languages': 15, 'spell_level': 9, 'learn_spell_chance': 100, 'max_spells_per_level': 100, 'spell_immunity': '6th LvL Illusions'},
        '25': {'num_languages': 20, 'spell_level': 9, 'learn_spell_chance': 100, 'max_spells_per_level': 100, 'spell_immunity': '7th LvL Illusions'}
    },
    'wisdom': {
        '1':  {'magic_defense': -6, 'bonus_spells':         '', 'spell_failure_chance': 80, 'spell_immunity': ''},
        '2':  {'magic_defense': -4, 'bonus_spells':         '', 'spell_failure_chance': 60, 'spell_immunity': ''},
        '3':  {'magic_defense': -3, 'bonus_spells':         '', 'spell_failure_chance': 50, 'spell_immunity': ''},
        '4':  {'magic_defense': -2, 'bonus_spells':         '', 'spell_failure_chance': 45, 'spell_immunity': ''},
        '5':  {'magic_defense': -1, 'bonus_spells':         '', 'spell_failure_chance': 40, 'spell_immunity': ''},
        '6':  {'magic_defense': -1, 'bonus_spells':         '', 'spell_failure_chance': 35, 'spell_immunity': ''},
        '7':  {'magic_defense': -1, 'bonus_spells':         '', 'spell_failure_chance': 30, 'spell_immunity': ''},
        '8':  {'magic_defense':  0, 'bonus_spells':         '', 'spell_failure_chance': 25, 'spell_immunity': ''},
        '9':  {'magic_defense':  0, 'bonus_spells':         '', 'spell_failure_chance': 20, 'spell_immunity': ''},
        '10': {'magic_defense':  0, 'bonus_spells':         '', 'spell_failure_chance': 15, 'spell_immunity': ''},
        '11': {'magic_defense':  0, 'bonus_spells':         '', 'spell_failure_chance': 10, 'spell_immunity': ''},
        '12': {'magic_defense':  0, 'bonus_spells':         '', 'spell_failure_chance':  5, 'spell_immunity': ''},
        '13': {'magic_defense':  0, 'bonus_spells':      '1st', 'spell_failure_chance':  0, 'spell_immunity': ''},
        '14': {'magic_defense':  0, 'bonus_spells':      '1st', 'spell_failure_chance':  0, 'spell_immunity': ''},
        '15': {'magic_defense':  1, 'bonus_spells':      '2nd', 'spell_failure_chance':  0, 'spell_immunity': ''},
        '16': {'magic_defense':  2, 'bonus_spells':      '2nd', 'spell_failure_chance':  0, 'spell_immunity': ''},
        '17': {'magic_defense':  3, 'bonus_spells':      '3rd', 'spell_failure_chance':  0, 'spell_immunity': ''},
        '18': {'magic_defense':  4, 'bonus_spells':      '4th', 'spell_failure_chance':  0, 'spell_immunity': ''},
        '19': {'magic_defense':  4, 'bonus_spells': '1st, 4th', 'spell_failure_chance':  0, 'spell_immunity': 'Cause Fear, Charm Person, Command, Friends, Hypnotism'},
        '20': {'magic_defense':  4, 'bonus_spells': '2nd, 4th', 'spell_failure_chance':  0, 'spell_immunity': 'Forget, Hold Person, Ray of Enfeeblement, Scare'},
        '21': {'magic_defense':  4, 'bonus_spells': '3rd, 5th', 'spell_failure_chance':  0, 'spell_immunity': 'Fear'},
        '22': {'magic_defense':  4, 'bonus_spells': '4th, 5th', 'spell_failure_chance':  0, 'spell_immunity': 'Charm Monster, Confusion, Emotion, Fumble, Suggestion'},
        '23': {'magic_defense':  4, 'bonus_spells': '5th, 5th', 'spell_failure_chance':  0, 'spell_immunity': 'Chaos, Feeblemind, Hold Monster, Magic Jar, Quest'},
        '24': {'magic_defense':  4, 'bonus_spells': '6th, 6th', 'spell_failure_chance':  0, 'spell_immunity': 'Geas, Mass Suggestion, Rod of Rulership'},
        '25': {'magic_defense':  4, 'bonus_spells': '6th, 7th', 'spell_failure_chance':  0, 'spell_immunity': 'Antipathy, Sympathy, Death Spell, Mass Charm'}
    },
    'charisma': {
        '1':  {'max_num_henchmen':  0, 'loyalty_base': -8, 'reaction_adjust': -7},
        '2':  {'max_num_henchmen':  1, 'loyalty_base': -7, 'reaction_adjust': -6},
        '3':  {'max_num_henchmen':  1, 'loyalty_base': -6, 'reaction_adjust': -5},
        '4':  {'max_num_henchmen':  1, 'loyalty_base': -5, 'reaction_adjust': -4},
        '5':  {'max_num_henchmen':  2, 'loyalty_base': -4, 'reaction_adjust': -3},
        '6':  {'max_num_henchmen':  2, 'loyalty_base': -3, 'reaction_adjust': -2},
        '7':  {'max_num_henchmen':  3, 'loyalty_base': -2, 'reaction_adjust': -1},
        '8':  {'max_num_henchmen':  3, 'loyalty_base': -1, 'reaction_adjust':  0},
        '9':  {'max_num_henchmen':  4, 'loyalty_base':  0, 'reaction_adjust':  0},
        '10': {'max_num_henchmen':  4, 'loyalty_base':  0, 'reaction_adjust':  0},
        '11': {'max_num_henchmen':  4, 'loyalty_base':  0, 'reaction_adjust':  0},
        '12': {'max_num_henchmen':  5, 'loyalty_base':  0, 'reaction_adjust':  0},
        '13': {'max_num_henchmen':  5, 'loyalty_base':  0, 'reaction_adjust':  1},
        '14': {'max_num_henchmen':  6, 'loyalty_base':  1, 'reaction_adjust':  2},
        '15': {'max_num_henchmen':  7, 'loyalty_base':  3, 'reaction_adjust':  3},
        '16': {'max_num_henchmen':  8, 'loyalty_base':  4, 'reaction_adjust':  5},
        '17': {'max_num_henchmen': 10, 'loyalty_base':  6, 'reaction_adjust':  6},
        '18': {'max_num_henchmen': 15, 'loyalty_base':  8, 'reaction_adjust':  7},
        '19': {'max_num_henchmen': 20, 'loyalty_base': 10, 'reaction_adjust':  8},
        '20': {'max_num_henchmen': 25, 'loyalty_base': 12, 'reaction_adjust':  9},
        '21': {'max_num_henchmen': 30, 'loyalty_base': 14, 'reaction_adjust': 10},
        '22': {'max_num_henchmen': 35, 'loyalty_base': 16, 'reaction_adjust': 11},
        '23': {'max_num_henchmen': 40, 'loyalty_base': 18, 'reaction_adjust': 12},
        '24': {'max_num_henchmen': 45, 'loyalty_base': 20, 'reaction_adjust': 13},
        '25': {'max_num_henchmen': 50, 'loyalty_base': 20, 'reaction_adjust': 14}
    }
}